# Site settings
title: Samtools
email: your-email@domain.com
description: "Samtools"
url: "http://www.htslib.org"
twitter_username: htslib
exclude: [CNAME, Dockerfile, Makefile, update_doc_md.pl]

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins: [jekyll-sitemap]
